'use client';

import { useState } from 'react';
import { useProjectStore } from '@/store/projectStore';
import { AddFileModal } from '@/components/projects/AddFileModal';
import { Folder, File, ChevronRight, ChevronDown, Sparkles, Plus, Trash2, MoreVertical } from 'lucide-react';

interface FileNode {
  name: string;
  type: 'file' | 'folder';
  path: string;
  children?: FileNode[];
  generatedBy?: string;
}

const mockFiles: FileNode[] = [
  {
    name: 'src',
    type: 'folder',
    path: '/src',
    children: [
      {
        name: 'components',
        type: 'folder',
        path: '/src/components',
        children: [
          { name: 'Button.tsx', type: 'file', path: '/src/components/Button.tsx' },
          { name: 'Modal.tsx', type: 'file', path: '/src/components/Modal.tsx' },
        ],
      },
      {
        name: 'pages',
        type: 'folder',
        path: '/src/pages',
        children: [
          { name: 'index.tsx', type: 'file', path: '/src/pages/index.tsx' },
          { name: 'profile.tsx', type: 'file', path: '/src/pages/profile.tsx', generatedBy: 'agent-2' },
        ],
      },
    ],
  },
  {
    name: 'package.json',
    type: 'file',
    path: '/package.json',
  },
];

export function FileTree() {
  const { currentProject, addFile, deleteFile } = useProjectStore();
  const [expanded, setExpanded] = useState<Set<string>>(new Set(['/src']));
  const [selected, setSelected] = useState<string>('');
  const [showAddFileModal, setShowAddFileModal] = useState(false);
  const [parentPath, setParentPath] = useState<string>('/');
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number; path: string } | null>(null);

  const toggleExpand = (path: string) => {
    const newExpanded = new Set(expanded);
    if (newExpanded.has(path)) {
      newExpanded.delete(path);
    } else {
      newExpanded.add(path);
    }
    setExpanded(newExpanded);
  };

  const renderNode = (node: FileNode, level: number = 0) => {
    const isExpanded = expanded.has(node.path);
    const isSelected = selected === node.path;

    return (
      <div key={node.path}>
        <div
          className={`flex items-center gap-1 px-2 py-1 cursor-pointer hover:bg-gray-700 ${
            isSelected ? 'bg-gray-700' : ''
          }`}
          style={{ paddingLeft: `${level * 16 + 8}px` }}
          onClick={() => {
            if (node.type === 'folder') {
              toggleExpand(node.path);
            } else {
              setSelected(node.path);
            }
          }}
          onContextMenu={(e) => handleContextMenu(e, node.path)}
        >
          {node.type === 'folder' ? (
            <>
              {isExpanded ? (
                <ChevronDown className="w-3 h-3 text-gray-400" />
              ) : (
                <ChevronRight className="w-3 h-3 text-gray-400" />
              )}
              <Folder className="w-4 h-4 text-blue-400" />
            </>
          ) : (
            <>
              <div className="w-4" />
              <File className="w-4 h-4 text-gray-400" />
            </>
          )}
          <span className="text-sm text-gray-300 ml-1">{node.name}</span>
          {node.generatedBy && (
            <Sparkles className="w-3 h-3 text-yellow-400 ml-auto" title="Generated by agent" />
          )}
        </div>
        {node.type === 'folder' && isExpanded && node.children && (
          <div>
            {node.children.map(child => renderNode(child, level + 1))}
          </div>
        )}
      </div>
    );
  };

  const handleContextMenu = (e: React.MouseEvent, path: string) => {
    e.preventDefault();
    setContextMenu({ x: e.clientX, y: e.clientY, path });
  };

  const handleAddFile = (parent: string) => {
    setParentPath(parent);
    setShowAddFileModal(true);
  };

  const handleDeleteFile = (fileId: string) => {
    if (currentProject && confirm('Are you sure you want to delete this file?')) {
      deleteFile(currentProject.id, fileId);
    }
    setContextMenu(null);
  };

  if (!currentProject) {
    return (
      <div className="p-4 text-center text-sm text-gray-400">
        <p>No project selected</p>
        <p className="text-xs mt-2">Create a project to get started</p>
      </div>
    );
  }

  return (
    <div className="p-2 relative">
      {/* Add File Button */}
      <div className="mb-2 px-2">
        <button
          onClick={() => handleAddFile('/')}
          className="w-full flex items-center gap-2 px-2 py-1.5 text-xs text-gray-400 hover:text-gray-200 hover:bg-gray-700 rounded"
        >
          <Plus className="w-3 h-3" />
          Add File/Folder
        </button>
      </div>

      {/* File Tree */}
      <div onContextMenu={(e) => e.preventDefault()}>
        {mockFiles.map(node => renderNode(node))}
      </div>

      {/* Add File Modal */}
      {showAddFileModal && currentProject && (
        <AddFileModal
          projectId={currentProject.id}
          parentPath={parentPath}
          onClose={() => {
            setShowAddFileModal(false);
            setParentPath('/');
          }}
        />
      )}

      {/* Context Menu */}
      {contextMenu && (
        <>
          <div
            className="fixed inset-0 z-40"
            onClick={() => setContextMenu(null)}
          />
          <div
            className="fixed z-50 bg-gray-800 border border-gray-700 rounded shadow-lg py-1 min-w-[150px]"
            style={{ left: contextMenu.x, top: contextMenu.y }}
          >
            <button
              onClick={() => {
                handleAddFile(contextMenu.path);
                setContextMenu(null);
              }}
              className="w-full text-left px-3 py-2 text-sm text-gray-300 hover:bg-gray-700 flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              Add File/Folder
            </button>
            <button
              onClick={() => handleDeleteFile(contextMenu.path)}
              className="w-full text-left px-3 py-2 text-sm text-red-400 hover:bg-gray-700 flex items-center gap-2"
            >
              <Trash2 className="w-4 h-4" />
              Delete
            </button>
          </div>
        </>
      )}
    </div>
  );
}

